Name = "webnames.ru"
Description = ''''''
URL = "https://webnames.ru/"
Code = "webnames"
Since = "v3.5.0"

Example = '''
WEBNAMES_APIKEY=xxxxxx \
lego --email myemail@example.com --dns webnames --domains my.example.org run
'''

[Configuration]
  [Configuration.Credentials]
    WEBNAMES_APIKEY = "API KEY"
  [Configuration.Additional]
    WEBNAMES_POLLING_INTERVAL = "Time between DNS propagation check"
    WEBNAMES_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    WEBNAMES_TTL = "The TTL of the TXT record used for the DNS challenge"
    WEBNAMES_HTTP_TIMEOUT = "API request timeout"

[Links]
  API = "https://www.webnames.ru/partner/api"
